# Generated by Django 5.1.3 on 2024-11-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя производства')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производства',
            },
        ),
        migrations.AddField(
            model_name='bicycle',
            name='edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bicycles.from'),
        ),
    ]
