# Generated by Django 5.1.3 on 2024-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_from_bicycle_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600, verbose_name='описание')),
                ('image', models.ImageField(upload_to='images_equipment/', verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'экипровка',
                'verbose_name_plural': 'экипировки',
            },
        ),
    ]
