# Generated by Django 5.1.3 on 2024-11-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0005_bicyclenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicyclenews',
            name='description',
            field=models.CharField(default='none', max_length=600, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='bicyclenews',
            name='image',
            field=models.ImageField(default='img', upload_to='images_bicycle_news/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='bicyclenews',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bicycles.tags'),
        ),
        migrations.AlterField(
            model_name='bicyclenews',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
