# Generated by Django 5.1.3 on 2024-11-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0006_bicyclenews_description_bicyclenews_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bicycles.country'),
        ),
        migrations.AlterField(
            model_name='bicyclenews',
            name='description',
            field=models.CharField(max_length=600, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='bicyclenews',
            name='image',
            field=models.ImageField(upload_to='images_bicycle_news/', verbose_name='изображение'),
        ),
    ]
