# Generated by Django 5.1.3 on 2024-11-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0007_alter_bicycle_country_alter_bicyclenews_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='название')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
            },
        ),
        migrations.AddField(
            model_name='bicycle',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='bicycles', to='bicycles.sizes', verbose_name='размер'),
        ),
    ]
