# Generated by Django 5.1.3 on 2024-12-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0009_categoryproduct_have_materialrams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='characters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bicycles.characters'),
        ),
    ]
