# Generated by Django 5.1.3 on 2024-12-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0010_bicycle_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bicycles.sizes'),
        ),
    ]
