# Generated by Django 5.1.3 on 2024-12-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0011_characters_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bicycles.from'),
        ),
    ]
