# Generated by Django 5.1.3 on 2024-12-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0012_alter_bicycle_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='category_product',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='bicycles', to='bicycles.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='category_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='bicycles_product', to='bicycles.categoryproduct'),
        ),
    ]
