# Generated by Django 5.1.3 on 2024-12-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0013_remove_bicycle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicycles.sizes'),
        ),
    ]
