# Generated by Django 5.1.3 on 2024-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0014_alter_characters_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата публикации'),
        ),
    ]
