# Generated by Django 5.1.3 on 2024-12-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0015_bicycle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
